resources:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: apps-dev-demo
    spec:
      project: default
      source:
        repoURL: "https://github.com/opspresso/argocd-env-demo"
        path: dev-demo/apps
        targetRevision: HEAD
      destination:
        server: "https://kubernetes.default.svc"
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

  # - apiVersion: argoproj.io/v1alpha1
  #   kind: Application
  #   metadata:
  #     name: sample-docs-prod
  #   spec:
  #     project: default
  #     source:
  #       repoURL: "https://github.com/opspresso/argocd-env-demo"
  #       path: sample-docs
  #       targetRevision: HEAD
  #       helm:
  #         valueFiles:
  #           - values-demo-prod.yaml
  #     destination:
  #       server: "https://kubernetes.default.svc"
  #       namespace: demo-prod
  #     syncPolicy:
  #       automated:
  #         prune: true
  #         selfHeal: true

  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: sample-node-dev
    spec:
      project: default
      source:
        repoURL: "https://github.com/opspresso/argocd-env-demo"
        path: sample-node
        targetRevision: HEAD
        helm:
          valueFiles:
            - values-demo-dev.yaml
      destination:
        server: "https://kubernetes.default.svc"
        namespace: demo-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: sample-node-prod
    spec:
      project: default
      source:
        repoURL: "https://github.com/opspresso/argocd-env-demo"
        path: sample-node
        targetRevision: HEAD
        helm:
          valueFiles:
            - values-demo-prod.yaml
      destination:
        server: "https://kubernetes.default.svc"
        namespace: demo-prod
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: sample-spring-dev
    spec:
      project: default
      source:
        repoURL: "https://github.com/opspresso/argocd-env-demo"
        path: sample-spring
        targetRevision: HEAD
        helm:
          valueFiles:
            - values-demo-dev.yaml
      destination:
        server: "https://kubernetes.default.svc"
        namespace: demo-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: sample-tomcat-dev
    spec:
      project: default
      source:
        repoURL: "https://github.com/opspresso/argocd-env-demo"
        path: sample-tomcat
        targetRevision: HEAD
        helm:
          valueFiles:
            - values-demo-dev.yaml
      destination:
        server: "https://kubernetes.default.svc"
        namespace: demo-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
